description: TLR Settings in a multi-tenant environment with Ð¡onsortia support enabled
type: "object"
properties:
  id:
    description: "ID of the ECS TLR Settings"
    $ref: "common/uuid.yaml"
  ecsTlrFeatureEnabled:
    description: "Indicates if TLR feature is enabled"
    type: boolean
required:
  - ecsTlrFeatureEnabled
